-- Generated by `db:generate`. Review before applying.

-- create table users
CREATE TABLE users ( id text NOT NULL PRIMARY KEY, email text NOT NULL, username text NOT NULL, password_hash text NOT NULL, global_role text NOT NULL, token_version integer NOT NULL DEFAULT 1, active numeric NOT NULL DEFAULT true, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create unique index idx_users_email
CREATE UNIQUE INDEX idx_users_email ON users(email);

-- create unique index idx_users_username
CREATE UNIQUE INDEX idx_users_username ON users(username);

-- create table workspaces
CREATE TABLE workspaces ( id text NOT NULL PRIMARY KEY, name text NOT NULL, created_by_user_id text NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create table workspace_memberships
CREATE TABLE workspace_memberships ( id text NOT NULL PRIMARY KEY, workspace_id text NOT NULL, user_id text NOT NULL, role text NOT NULL, created_by_user_id text NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create unique index idx_workspace_memberships_workspace_user
CREATE UNIQUE INDEX idx_workspace_memberships_workspace_user ON workspace_memberships(workspace_id, user_id);

