-- Generated by `db:generate`. Review before applying.

-- create table collection_environment_policies
CREATE TABLE collection_environment_policies ( id text NOT NULL PRIMARY KEY, workspace_id text NOT NULL, collection_id text NOT NULL, environment_id text NOT NULL, default_environment numeric NOT NULL DEFAULT false, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create index idx_collection_env_policies_workspace_collection
CREATE INDEX idx_collection_env_policies_workspace_collection ON collection_environment_policies(workspace_id, collection_id);

-- create unique index idx_collection_env_policies_collection_environment
CREATE UNIQUE INDEX idx_collection_env_policies_collection_environment ON collection_environment_policies(collection_id, environment_id);

