-- Generated by `db:generate`. Review before applying.

-- create table resource_grants
CREATE TABLE resource_grants ( id text NOT NULL PRIMARY KEY, workspace_id text NOT NULL, user_id text NOT NULL, resource_type text NOT NULL, resource_id text NOT NULL, access_level text NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create unique index idx_resource_grants_workspace_user_resource
CREATE UNIQUE INDEX idx_resource_grants_workspace_user_resource ON resource_grants(workspace_id, user_id, resource_type, resource_id);

