-- Generated by `db:generate`. Review before applying.

-- requests.query_params_json: add column query_params_json text NOT NULL DEFAULT '[]'
ALTER TABLE `requests` ADD COLUMN query_params_json text NOT NULL DEFAULT '[]';

-- requests.headers_json: add column headers_json text NOT NULL DEFAULT '[]'
ALTER TABLE `requests` ADD COLUMN headers_json text NOT NULL DEFAULT '[]';

-- requests.body: add column body text NOT NULL DEFAULT ''
ALTER TABLE `requests` ADD COLUMN body text NOT NULL DEFAULT '';

-- requests.body_language: add column body_language text NOT NULL DEFAULT json
ALTER TABLE `requests` ADD COLUMN body_language text NOT NULL DEFAULT json;

-- requests.auth_config_json: add column auth_config_json text NOT NULL DEFAULT '{}'
ALTER TABLE `requests` ADD COLUMN auth_config_json text NOT NULL DEFAULT '{}';

