-- Generated by `db:generate`. Review before applying.

-- create table collections
CREATE TABLE collections ( id text NOT NULL PRIMARY KEY, workspace_id text NOT NULL, name text NOT NULL, icon text NOT NULL DEFAULT PhGlobe, sort_order integer NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create unique index idx_collections_workspace_name
CREATE UNIQUE INDEX idx_collections_workspace_name ON collections(workspace_id, name);

-- create table requests
CREATE TABLE requests ( id text NOT NULL PRIMARY KEY, collection_id text, workspace_id text NOT NULL, method text NOT NULL DEFAULT GET, name text NOT NULL, path text NOT NULL, sort_order integer NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create index idx_requests_collection
CREATE INDEX idx_requests_collection ON requests(collection_id);

-- create table environments
CREATE TABLE environments ( id text NOT NULL PRIMARY KEY, workspace_id text NOT NULL, name text NOT NULL, visibility text NOT NULL DEFAULT project, sort_order integer NOT NULL DEFAULT 0, created_by_user_id text NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create unique index idx_environments_workspace_name
CREATE UNIQUE INDEX idx_environments_workspace_name ON environments(workspace_id, name);

-- create table environment_variables
CREATE TABLE environment_variables ( id text NOT NULL PRIMARY KEY, environment_id text NOT NULL, key text NOT NULL, value text NOT NULL DEFAULT '', secret numeric NOT NULL DEFAULT false, sort_order integer NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL );

-- create unique index idx_variables_env_key
CREATE UNIQUE INDEX idx_variables_env_key ON environment_variables(environment_id, key);

