package gormstorage

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"gorm.io/gorm"
)

type MigrationFile struct {
	Version string
	Name    string
	Path    string
}

func GenerateMigrationPlan(db *gorm.DB, dir string) (SchemaPlan, error) {
	files, err := listMigrationFiles(dir)
	if err != nil {
		return SchemaPlan{}, err
	}
	if len(files) == 0 {
		return Plan(db)
	}

	devDB, err := openInMemoryDB()
	if err != nil {
		return SchemaPlan{}, err
	}
	sqlDB, err := devDB.DB()
	if err != nil {
		return SchemaPlan{}, err
	}
	defer sqlDB.Close()

	if err := applyMigrationFileList(devDB, files, false); err != nil {
		return SchemaPlan{}, err
	}

	return Plan(devDB)
}

func GenerateMigrationFile(dir string, name string, plan SchemaPlan, now time.Time) (string, error) {
	if !plan.HasChanges() {
		return "", nil
	}
	if plan.HasManualChanges() {
		return "", fmt.Errorf("%w:\n%s", ErrManualMigrationRequired, plan.String())
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}

	filename := now.UTC().Format("20060102150405") + "_" + sanitizeMigrationName(name) + ".sql"
	path := filepath.Join(dir, filename)
	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf("migration file already exists: %s", path)
	}

	var builder strings.Builder
	builder.WriteString("-- Generated by `db:generate`. Review before applying.\n\n")
	for _, change := range plan.SafeChanges() {
		if change.SQL == "" {
			continue
		}
		builder.WriteString("-- ")
		builder.WriteString(change.Description)
		builder.WriteString("\n")
		builder.WriteString(strings.TrimRight(change.SQL, " ;"))
		builder.WriteString(";\n\n")
	}

	if err := os.WriteFile(path, []byte(builder.String()), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

func PendingMigrationPlan(db *gorm.DB, dir string) (SchemaPlan, error) {
	files, err := pendingMigrationFiles(db, dir)
	if err != nil {
		return SchemaPlan{}, err
	}
	if len(files) == 0 {
		return SchemaPlan{}, nil
	}

	plan := SchemaPlan{Changes: make([]Change, 0, len(files))}
	for _, file := range files {
		plan.Changes = append(plan.Changes, Change{
			Safety:      SafeChange,
			Description: "apply migration " + file.Name,
			SQL:         file.Path,
		})
	}

	return plan, nil
}

func ApplyMigrationFiles(db *gorm.DB, dir string) error {
	files, err := pendingMigrationFiles(db, dir)
	if err != nil {
		return err
	}

	return applyMigrationFileList(db, files, true)
}

func applyMigrationFileList(db *gorm.DB, files []MigrationFile, recordApplied bool) error {
	return db.Transaction(func(tx *gorm.DB) error {
		if recordApplied {
			if err := ensureSchemaMigrationsTable(tx); err != nil {
				return err
			}
		}

		for _, file := range files {
			if err := applyMigrationFile(tx, file, recordApplied); err != nil {
				return err
			}
		}

		return nil
	})
}

func applyMigrationFile(tx *gorm.DB, file MigrationFile, recordApplied bool) error {
	statements, err := readSQLStatements(file.Path)
	if err != nil {
		return err
	}
	for _, statement := range statements {
		if strings.TrimSpace(statement) == "" {
			continue
		}
		if err := tx.Exec(statement).Error; err != nil {
			return fmt.Errorf("%s: %w", file.Name, err)
		}
	}
	if !recordApplied {
		return nil
	}
	if err := tx.Exec("INSERT INTO schema_migrations (version, name, applied_at) VALUES (?, ?, ?)", file.Version, file.Name, time.Now().UTC()).Error; err != nil {
		return err
	}

	return nil
}

func pendingMigrationFiles(db *gorm.DB, dir string) ([]MigrationFile, error) {
	files, err := listMigrationFiles(dir)
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, nil
	}

	applied, err := appliedMigrationVersions(db)
	if err != nil {
		return nil, err
	}

	pending := make([]MigrationFile, 0, len(files))
	for _, file := range files {
		if !applied[file.Version] {
			pending = append(pending, file)
		}
	}

	return pending, nil
}

func listMigrationFiles(dir string) ([]MigrationFile, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	files := make([]MigrationFile, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".sql") {
			continue
		}

		version, _, found := strings.Cut(entry.Name(), "_")
		if !found || version == "" {
			return nil, fmt.Errorf("invalid migration filename %q", entry.Name())
		}

		files = append(files, MigrationFile{
			Version: version,
			Name:    entry.Name(),
			Path:    filepath.Join(dir, entry.Name()),
		})
	}

	sort.Slice(files, func(i int, j int) bool {
		return files[i].Name < files[j].Name
	})

	return files, nil
}

func appliedMigrationVersions(db *gorm.DB) (map[string]bool, error) {
	applied := make(map[string]bool)
	if !db.Migrator().HasTable("schema_migrations") {
		return applied, nil
	}

	var rows []struct {
		Version string `gorm:"column:version"`
	}
	if err := db.Raw("SELECT version FROM schema_migrations").Scan(&rows).Error; err != nil {
		return nil, err
	}
	for _, row := range rows {
		applied[row.Version] = true
	}

	return applied, nil
}

func ensureSchemaMigrationsTable(db *gorm.DB) error {
	return db.Exec(`CREATE TABLE IF NOT EXISTS schema_migrations (
		version TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		applied_at DATETIME NOT NULL
	)`).Error
}

func readSQLStatements(path string) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	statements := make([]string, 0)
	var builder strings.Builder
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(strings.TrimSpace(line), "--") {
			continue
		}
		builder.WriteString(line)
		builder.WriteString("\n")
		if strings.HasSuffix(strings.TrimSpace(line), ";") {
			statements = append(statements, builder.String())
			builder.Reset()
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if strings.TrimSpace(builder.String()) != "" {
		statements = append(statements, builder.String())
	}

	return statements, nil
}

func sanitizeMigrationName(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	name = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(name, "_")
	name = strings.Trim(name, "_")
	if name == "" {
		return "schema"
	}

	return name
}
